---
output: html_document
---

##### **7.3.1.1.** Cette étape permet d'enregistrer un objet dans R avec les informations de toutes les cellules existantes.

```r
shp_cells <- rgdal::readOGR(dsn="./shp",
                            layer="Cellule_terrain_2016-2020") # Ici le fichier shapefile est placé dans un dossier shp et on appelle tous les fichiers nommés "Cellule_terrain_2016_2020"
```

##### **7.3.1.2.** Cette étape permet d'extraire les informations nécessaires concernant les nouvelles cellules et de formater ces informations de sorte à pouvoir les insérer dans Coléo.

```r
# Création d'une liste vide pour l'objet final
shp_cells_list <- list()

for (i in 1:length(cell_abs)){

# Obtention des information pour un cellule
  shp <- shp_cells[shp_cells$IJ == cell_abs[i] ,]

# Création d'une liste avec les informations nécessaires pour chaque cellule
  cells_ls <- list()
  cells_ls$cell_code <- cell_abs[i] # Code de la cellule
  cells_ls$name <- unique(shp_cells[shp_cells$IJ == cell_abs[i] & !is.na(shp_cells$Nom),]@data$Nom) # Nom de la cellule

  if(identical(cells_ls$name, character(0))){
    cells_ls$name <- NULL
  } # Information absente si pas de nom pour la cellule

# Création de l'objet spatial pour les coordonnées de la cellule
  shp_sp <- as(shp, "SpatialPolygons")
  cells_ls$geom <- geojsonio::geojson_list(shp)$features[[1]]$geometry # Caractéristiques de l'objet spatial
  cells_ls$geom$crs <- list(type="name",properties=list(name="EPSG:4326")) # Information sur le systême de coordonnées de référence (CRS)

# Alimentation de l'objet final avec un niveau pour chaque cellule
  shp_cells_list[[i]] <- cells_ls
}
```

##### **7.3.1.3.** Nous pouvons maintenant insérer les nouvelles cellules dans la base de données Coléo.

```r
# Envoyer la liste de nouvelles cellules vers Coléo
COLEO_cells <- post_cells(shp_cells_list)
```

La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

##### **7.3.1.4.** ATTENTION, finissez en faisant la mise à jour de la liste des cellules présentes dans Coléo.

```r
# Mise à jour de la liste des cellules provenant de Coléo
cells <- rcoleo::get_cells()
cells <- do.call("rbind", cells[[1]]$body)
```
