---
title: "Tutoriel pour injection des campagnes Insecgs Sol"
author: "Andrew MacDonald"
date: "novembre 2020"
output: html_document
---

## 1. Créer une base de données excel

Afin d'injecter des nouvelles campagnes *insects sol* dans la base de données Coléo, vous devez regrouper les informations suivantes dans un fichier excel :



|nom de variable |meaning |
|:-----------|:-------|
|nom_cellule                   |  Name of the cell      |
|no_de_reference_de_la_cellule |  code numérique unique pour chaque cellule      |
|no_de_reference_du_site       |  code alpha-numérique unique du site      |
|type_milieu                   |  'lac', 'rivière', 'forestier', 'marais', 'marais côtier', 'toundrique', 'tourbière'      |
|type_identification           |  `TRI` ou `ID`      |
|no_echantillon                |  Sample number (MFFP syntax)      |
|date_debut                    |  date du début du prélèvement      |
|date_fin                      |   date de la fin du prélèvement      |
|nom_scientifique              |  nom latin des espèces observées      |
|abondance                     |  Count of observation.      |


soil insect data is actually two different kinds of data. 

|nm                            |meaning |
|:-----------------------------|:-------|
|nom_cellule                   | Name of the cell         |
|no_de_reference_de_la_cellule | code numérique unique pour chaque cellule       |
|no_de_reference_du_site       | code alpha-numérique unique du site       |
|type_milieu                   |        |
|date_debut                    |  date du début du prélèvement      |
|date_fin                      |  date de la fin du prélèvement     |
|technicien_1                  |  name of the technician involved       |
|technicien_2                  |        |
|code_piege                    |  MFFP code for the trap in question      |
|latitude                      |        |
|longitude                     |        |
|no_echantillon                |        |
|date_de_collecte              |        |

Note that soil insects are peculiar, in that unlike other datasets in coleo they produce two kinds of data. First, soil insects which are sorted to species -- and second, soil insects which are not identified to species. More on this below

Note : ne pas laisser de case vide, inscrire NA lorsque nécessaire
Note bis : Il est essentiel que ce tableau ne contiennent QUE des nouvelles campagnes ! Sous peine de voir échoué le code qui suit.



## 2. Corriger la base de données

Il est très important de s'assurer que la base de données excel soit sans erreur **avant** de l'injecter dans Coléo. Coléo n'a pas de système de correction et va prendre toutes les entrées, même si elles contiennent des erreurs.


## 3. Créer un projet R

Dans RStudio,

* Aller dans `File` > `New Project` > `New Directory` > `New Project`
* Choisir un nom de projet et un lieu dans les fichiers pour le projet

Les projets permettent de travailler dans un répertoire de travail (*working directory*). La base de données doit donc être sauvegardée dans le même dossier que le projet afin de faire parti du répertoire de travail.

## 4. Sauvegarder la base de données en format .csv dans le même dossier que le projet R

<div class = "blue">

**Rappel** - L'encodage du fichier .csv doit être en "UTF-8"

</div>

## 5. Installer et charger les packages nécessaires

S'il ne s'agit pas de vos premières injections dans Coléo avec R, vous pouvez directement passer à l'**étape 5.2**. Sinon vous devez installer les packages nécessaires. 

### 5.1. Installation des packages

Dans RStudio :

```r
install.packages("devtools")
install.packages("dplyr")
```

Pour installer le package `rcoleo`, il faut utiliser le package `devtools`, il faut donc l'appeller avec `library()`

```r
library(devtools)
# Installation du package rcoleo à partir de github
install_github("TheoreticalEcosystemEcology/rcoleo") 
```

### 5.2. Chargement des packages

```r
install.packages("rcoleo")
install.packages("dplyr")
```

## 6. Mettre en cache son jeton d'accès

Ce jeton permet d'apporter des modifications dans Coléo. Il est unique et se retrouve dans Coléo, sous le profil de l'utilisateur dans le menu à gauche.

```r
saveRDS("votrejeton",".httr-oauth")
```

Cette étape n'est faite qu'une fois et permet l'enregistrement de votre jeton dans le répertoire du projet R. Une fois faite, elle est supprimée du code d'injection. Le jeton est confidentiel.


## 7. Vérification pré-injection

La succession d'étape qui suivent permettent de vérifier si les cellules, les sites, les noms d'espèces et les attributs associés aux campagnes à injecter existent déjà dans Coléo.

### 7.1. Création d'un objet R avec les nouvelles campagnes à insérer dans Coléo

```r
camp <- read.csv("./lenomdevotrebasededonnées.csv",
                 header = TRUE,
                 sep = ',',
                 stringsAsFactors = FALSE,
                 encoding = "UTF-8") # l'encoding UTF-8 permet de garder les accents
```
### 7.2. Acquisition de la liste des cellules, des sites, des noms d'espèce de référence et des attributs déjà présentes dans Coléo et création d'un objet R pour chacune

```r
# Acquisition cellules Coléo
cells <- rcoleo::get_cells()
cells <- do.call("rbind", cells[[1]]$body)

# Acquisition sites Coléo
sites <- rcoleo::get_sites()
sites <- do.call("rbind", sites[[1]]$body)

# Acquisition nom espèces Coléo
species <- rcoleo::get_species()
species <- do.call("rbind", species[[1]]$body)

# Acquisition des attributs dans Coléo
attrs <- rcoleo::get_gen("/attributes")
attrs <- do.call("rbind.fill", attrs$body)
```

### 7.3. Vérification de l'existence des cellules, sites, noms d'espèces et des attributs associés aux nouvelles campagnes dans Coléo

#### 7.3.1. Pour les cellules

```r
# Test pour vérifier l'existence des cellules dans Coléo
cell_abs <- rcoleo::COLEO_comp(unique(camp$cell_code),
                               unique(cells$cell_code))
cell_abs
```

La sortie R vous indique si vous pouvez passer à l'étape suivante ou non. Dans le cas où certaines cellules n'existent pas dans Coléo, il sera nécessaire d'importer ces cellules avant de continuer l'insertions des nouvelles campagnes. Pour ce faire, vous utilisez l'objet `cell_abs` que vous venez de créer et qui contient la liste des cellules à créer et suivre les étapes détaillées en déroulant la vignette **Injection des cellules** ci-dessous.

<script>
function myFunction1() {
    var x = document.getElementById("myDIV_cells");
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>
 
<div id="myDIV_cells">


##### **7.3.1.1.** Cette étape permet d'enregistrer un objet dans R avec les informations de toutes les cellules existantes.

```r
shp_cells <- rgdal::readOGR(dsn="./shp",
                            layer="Cellule_terrain_2016-2020") # Ici le fichier shapefile est placé dans un dossier shp et on appelle tous les fichiers nommés "Cellule_terrain_2016_2020"
```

##### **7.3.1.2.** Cette étape permet d'extraire les informations nécessaires concernant les nouvelles cellules et de formater ces informations de sorte à pouvoir les insérer dans Coléo.

```r
# Création d'une liste vide pour l'objet final
shp_cells_list <- list()

for (i in 1:length(cell_abs)){

# Obtention des information pour un cellule
  shp <- shp_cells[shp_cells$IJ == cell_abs[i] ,]

# Création d'une liste avec les informations nécessaires pour chaque cellule
  cells_ls <- list()
  cells_ls$cell_code <- cell_abs[i] # Code de la cellule
  cells_ls$name <- unique(shp_cells[shp_cells$IJ == cell_abs[i] & !is.na(shp_cells$Nom),]@data$Nom) # Nom de la cellule

  if(identical(cells_ls$name, character(0))){
  
    cells_ls$name <- NULL
    
  } # Information absente si pas de nom pour la cellule

# Création de l'objet spatial pour les coordonnées de la cellule
  shp_sp <- as(shp, "SpatialPolygons")
  cells_ls$geom <- geojsonio::geojson_list(shp)$features[[1]]$geometry # Caractéristiques de l'objet spatial
  cells_ls$geom$crs <- list(type = "name",
                            properties = list(name = "EPSG:4326")) # Information sur le systême de coordonnées de référence (CRS)

# Alimentation de l'objet final avec un niveau pour chaque cellule
  shp_cells_list[[i]] <- cells_ls
}
```

##### **7.3.1.3.** Nous pouvons maintenant insérer les nouvelles cellules dans la base de données Coléo.

```r
# Envoi de la liste de nouvelles cellules vers Coléo
COLEO_cells <- post_cells(shp_cells_list)
```

La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

##### **7.3.1.4.** ATTENTION, finissez en faisant la mise à jour de la liste des cellules présentes dans Coléo.

```r
# Mise à jour de la liste des cellules provenant de Coléo
cells <- rcoleo::get_cells()
cells <- do.call("rbind", cells[[1]]$body)
```
 
</div>

<script>
document.getElementById("myDIV_cells").style.display ="none"
</script>

<button onclick="myFunction1()">Vignette Injection des cellules</button>

Vous pouvez maintenant récupérer l'ID unique des cellules.

```r
camp <- dplyr::left_join(camp,
                         cells[, c("id", "cell_code")],
                         by = "cell_code")
names(camp)[names(camp) == "id"] <- "cell_id"
```

#### 7.3.2. Pour les sites

```r
# Test pour vérifier l'existence des sites dans Coléo
site_abs <- rcoleo::COLEO_comp(unique(camp$site_code),
                               unique(sites$site_code))
site_abs
```

La sortie R vous indique si vous pouvez passer à l'étape suivante ou non. Dans le cas où certains sites n'existent pas dans Coléo, il sera nécessaire d'importer ces sites avant de continuer l'insertions des nouvelles campagnes. Pour ce faire, vous utilisez l'objet `site_abs` que vous venez de créer et qui contient la liste des cellules à créer et suivre les étapes détaillées en déroulant la vignette **Injection des sites** ci-dessous.

<script>
function myFunction2() {
    var x = document.getElementById("myDIV_sites");
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>

<div id="myDIV_sites">


##### **7.3.2.1.** Cette étape permet de sélectionner les informations nécessaires pour les sites absents de Coléo.

```r
# Sélection des lignes du tableau concernant les sites manquants
site_df <- camp[camp$site_code %in% site_abs, c("cell_id", "site_code", "type_hab", "opened_at", "lat", "lon")]

# Retrait des lignes dupliquées
site_df <- site_df[!duplicated(site_df),]

# Changement du nom de la variable "type_hab" pour correspondre à celle de Coléo ("type")
names(site_df)[names(site_df) == "type_hab"] <- "type"

# Création de la variable geom à partir des variables "lat" & "lon"
site_df_ls <- apply(site_df, 1, as.list) # Création de la liste
str(site_df_ls) # Vérification de la structure de l'objet

geom <- apply(site_df,1, function(x){

  if(!any(is.na(x["lat"]), is.na(x["lon"]))){
  
    return(geojsonio::geojson_list(as.numeric(c(x["lon"], x["lat"])))$features[[1]]$geometry)
    
  } else {
  
    return(NA)
    
  }})

for(i in 1:length(site_df_ls)){ # Fusionner les deux listes (geomations + sites)

  site_df_ls[[i]]$geom <- geom[i][[1]]
  if(is.list(site_df_ls[[i]]$geom)){
  
    site_df_ls[[i]]$geom$crs <- list(type = "name",
                                     properties = list(name="EPSG:4326"))
  }
}
```
##### **7.3.2.2.** Nous pouvons maintenant insérer les nouveaux sites dans la base de données Coléo.
```r
# Envoi de la liste des nouveaux sites vers Coléo
COLEO_sites <- rcoleo::post_sites(site_df_ls)
```

La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

##### **7.3.2.3.** ATTENTION, finissez en faisant la mise à jour de la liste des sites présents dans Coléo.

```r
# Mise à jour de la liste des sites provenant de Coléo
sites <- rcoleo::get_sites()
sites <- do.call("rbind", sites[[1]]$body)
```
</div>

<script>
document.getElementById("myDIV_sites").style.display ="none"
</script> 

<button onclick="myFunction2()">Vignette Injection des sites</button>

Vous pouvez maintenant récupérer l'ID unique des sites.

```r
camp <- dplyr::left_join(camp,
                         sites[, c("id", "site_code")],
                         by = "site_code")
names(camp)[names(camp) == "id"] <- "site_id"
```


#### 7.3.3. Pour les noms d'espèces

```r
# Test pour vérifier l'existence des noms des espèces dans Coléo
sp_abs <- rcoleo::COLEO_comp(unique(camp$taxa_name),
                             unique(species$name))
sp_abs
```

La sortie R vous indique si vous pouvez passer à l'étape suivante ou non. Dans le cas où certains noms d'espèces n'existent pas dans Coléo, il sera nécessaire d'importer ces noms avant de continuer l'insertions des nouvelles campagnes. Pour ce faire, vous utilisez l'objet `sp_abs` que vous venez de créer et qui contient la liste des cellules à créer et suivre  les étapes détaillées dans la vignette **Injection des noms d'espèce**.

<script>
function myFunction3() {
    var x = document.getElementById("myDIV_taxa");
    if (x.style.display === "none") {
        x.style.display = "block";
    } else {
        x.style.display = "none";
    }
}
</script>

<div id="myDIV_taxa">

##### **7.3.3.1.** Cette étape permet de sélectionner les informations nécessaires pour les noms d'espèce absents de Coléo.

```r
# Formatage du tableau à insérer
taxa_df <- camp[camp$taxa_name %in% sp_abs,]
taxa_df <- select(taxa_df,
                    name = taxa_name,
                    vernacular_fr) # colonnes nécessaires
```
##### **7.3.3.2.** Cette étape permet de formatter les données afin de pouvoir les injecter dans la base de données Coléo.

```r
# Retrait des lignes dupliquées
taxa_df <- taxa_df[!duplicated(taxa_df),] 

# Formatage des données sous forme de liste
taxa_df_ls <- apply(taxa_df, 1, as.list)
```
##### **7.3.3.3.** On injecte dans la base de données Coléo.
```r
# Injection
COLEO_taxa <- rcoleo::post_species(taxa_df_ls)
```

***ATTENTION*** Réfléchir au fait que toutes les informations pour les espèces ne sont pas renseignées avec cette méthode
</div>

<script>
document.getElementById("myDIV_taxa").style.display ="none"
</script> 

<button onclick="myFunction3()">Vignette injection noms d'espèce</button>

#### 7.3.3. Pour les attributs

```r
# Contenu de la table des attributs dans Coléo
attrs
```
Vérifier si les attributs nécessaires à vos campagnes sont bien présents dans cette table.


### 7.4 Optimisation du tableau à injecter initial

```r
# Ajout du site_id
camp <- dplyr::left_join(camp, sites[, c("id", "site_code")], by = "site_code")
names(camp)[names(camp) == "id"] <- "site_id"
```




## 7. Vérification pré-injection

La succession d'étape qui suivent permettent de vérifier si les cellules, les sites et les noms d'espèces associés aux campagnes à injecter existent déjà dans Coléo.

### 7.1. Création d'un objet R avec les nouvelles campagnes à insérer dans Coléo






```r
library(googlesheets4)
library(tidyverse)

options(gargle_oauth_email = TRUE)
gs4_auth()
insecte_sol_obs <- range_read(sheet_address,
                              sheet = "insecte_sol_observation")

glimpse(insecte_sol_obs)
```

```
## Rows: 1,940
## Columns: 10
## $ nom_cellule                   [3m[38;5;246m<chr>[39m[23m "Bellechasse (A)", "Bellechasse (A)", "Bellechasse (A)", "Bellec…
## $ no_de_reference_de_la_cellule [3m[38;5;246m<chr>[39m[23m "141_108", "141_108", "141_108", "141_108", "141_108", "141_108"…
## $ no_de_reference_du_site       [3m[38;5;246m<chr>[39m[23m "141_108_F01", "141_108_F01", "141_108_F01", "141_108_F01", "141…
## $ type_milieu                   [3m[38;5;246m<chr>[39m[23m "Forestier", "Forestier", "Forestier", "Forestier", "Forestier",…
## $ type_identification           [3m[38;5;246m<chr>[39m[23m "ID", "ID", "ID", "ID", "ID", "ID", "ID", "ID", "ID", "ID", "TRI…
## $ no_echantillon                [3m[38;5;246m<chr>[39m[23m "2016-0020", "2016-0020", "2016-0021", "2016-0022", "2016-0024",…
## $ date_debut                    [3m[38;5;246m<list>[39m[23m [2016-05-26, 2016-05-26, 2016-05-26, 2016-05-26, 2016-05-26, 20…
## $ date_fin                      [3m[38;5;246m<dttm>[39m[23m 2016-06-20, 2016-06-20, 2016-06-20, 2016-07-20, 2016-07-20, 201…
## $ nom_scientifique              [3m[38;5;246m<chr>[39m[23m "Pterostichus pensylvanicus", "Notiophilus aeneus", "Melandryida…
## $ abondance                     [3m[38;5;246m<dbl>[39m[23m 1, 1, 1, 2, 1, 1, 3, 37, 1, 1, 42, 12, 4, 22, 31, 5, 16, 3, 1, 1…
```

```r
insecte_sol_piege <-  range_read(sheet_address,
                              sheet = "insecte_sol_info_piege",
                              na = "NA",
                              col_types = "ccccDDcccnncD")

insecte_sol_piege
```

```
## # A tibble: 517 x 13
##    nom_cellule no_de_reference… no_de_reference… type_milieu date_debut date_fin   technicien_1
##    <chr>       <chr>            <chr>            <chr>       <date>     <date>     <chr>       
##  1 Mékinac (B) 135_104          135_104_F01      forestier   2016-05-20 2016-07-12 Caroline Du…
##  2 Mékinac (B) 135_104          135_104_F01      forestier   2016-05-20 2016-07-12 Caroline Du…
##  3 Mékinac (B) 135_104          135_104_F01      forestier   2016-05-20 2016-07-12 Caroline Du…
##  4 Mékinac (B) 135_104          135_104_F01      forestier   2016-05-20 2016-07-12 Caroline Du…
##  5 Mékinac (B) 135_104          135_104_F01      forestier   2016-05-20 2016-07-12 Caroline Du…
##  6 Mékinac (B) 135_104          135_104_F01      forestier   2016-05-20 2016-07-12 Caroline Du…
##  7 Lac Simonc… 132_116          132_116_F01      forestier   2016-06-03 2016-07-25 Caroline Du…
##  8 Lac Simonc… 132_116          132_116_F01      forestier   2016-06-03 2016-07-25 Caroline Du…
##  9 Lac Simonc… 132_116          132_116_F01      forestier   2016-06-03 2016-07-25 Caroline Du…
## 10 Bellechass… 141_108          141_108_F01      forestier   2016-05-26 2016-07-20 Caroline Du…
## # … with 507 more rows, and 6 more variables: technicien_2 <chr>, code_piege <chr>, latitude <dbl>,
## #   longitude <dbl>, no_echantillon <chr>, date_de_collecte <date>
```

```r
glimpse(insecte_sol_piege)
```

```
## Rows: 517
## Columns: 13
## $ nom_cellule                   <chr> "Mékinac (B)", "Mékinac (B)", "Mékinac (B)", "Mékinac (B)", "Mék…
## $ no_de_reference_de_la_cellule <chr> "135_104", "135_104", "135_104", "135_104", "135_104", "135_104"…
## $ no_de_reference_du_site       <chr> "135_104_F01", "135_104_F01", "135_104_F01", "135_104_F01", "135…
## $ type_milieu                   <chr> "forestier", "forestier", "forestier", "forestier", "forestier",…
## $ date_debut                    <date> 2016-05-20, 2016-05-20, 2016-05-20, 2016-05-20, 2016-05-20, 201…
## $ date_fin                      <date> 2016-07-12, 2016-07-12, 2016-07-12, 2016-07-12, 2016-07-12, 201…
## $ technicien_1                  <chr> "Caroline Dube", "Caroline Dube", "Caroline Dube", "Caroline Dub…
## $ technicien_2                  <chr> NA, NA, NA, NA, NA, NA, "Pierre-Alexis Drolet", "Pierre-Alexis D…
## $ code_piege                    <chr> "MP-05", "MP-06", "MP-07", "MP-05", "MP-06", "MP-07", "MP-12", "…
## $ latitude                      <dbl> 46.79415, 46.79401, 46.79410, 46.79415, 46.79401, 46.79410, 48.2…
## $ longitude                     <dbl> -72.30296, -72.30310, -72.30336, -72.30296, -72.30310, -72.30336…
## $ no_echantillon                <chr> "2016-0007", "2016-0008", "2016-0009", "2016-0011", "2016-0012",…
## $ date_de_collecte              <date> 2016-06-10, 2016-06-10, 2016-06-10, 2016-07-12, 2016-07-12, 201…
```

Note that in this example I am reading from google drive. If your spreadsheet is in a text format, remember to use `encoding = "UTF-8"`.

You can facilitate your work below by controlling the type of columns when you read them in.
Here I use the argument `col_types` to accomplish this. see `?readr::read_csv`


Here we can see that the columns of the dataset match what is above. 


## 8. Injections des nouvelles campagnes *insectes_sol*

Pour une injection complète d'une campagne, il est nécessaire de passer par l'importation d'informations successives dans différentes tables de Coléo. La hiérarchie des tables à renseigner est cruciale, sans quoi l'injection de la campagne est vouée à l'échec. Les prochaines étapes détaillent l'ajout d'information dans les tables:

1. Campagnes ("*/campaigns*")
2. Repères ("*/landmarks*")
3. Observations ("*/observations*")
4. Observations des espèces ("*/obs_species*")

### 8.1. Injections des informations sur les nouvelles campagnes

Les champs qui peuvent être remplis dans la table **campagnes** ("/campaigns") de Coléo sont les suivants (les champs en gras sont obligatoires) :

* **site_id** : à récupérer dans Coléo
* **type** : nom de la campagne, ici "zooplanctons"
* **technicians** : liste composée de "technicien_1" et "technicien_2"
* **opened_at** : corresppond à "date_debut"
* **closed_at** : correspond à "date_fin"
* *notes*

#### 8.1.1. On commence par séléctionner les champs d'interêts & on matche les noms de variables avec celles de Coléo.


```r
inj_camp_insects <- dplyr::select(insecte_sol_piege, 
                               site_code = no_de_reference_du_site, 
                               opened_at = date_debut, 
                               closed_at = date_fin, 
                               technicien_1, 
                               technicien_2)
```

#### 8.1.2. On garde une ligne unique par nouvelle campagne.

```r
inj_camp_insects
```

#### 8.1.3. On récupère le `site_id`, nécessaire à l'injection.

```r
inj_camp_zoop <- dplyr::left_join(inj_camp_zoop, sites[, c(1,4)], by = "site_code")
names(inj_camp_zoop)[6] <- "site_id"
```

#### 8.1.4. On créé une liste pour le nom des technicien/ne/s.

```r
tech <- list() # Création d'un objet `list` vide

for(i in 1:length(inj_camp_zoop$site_code)){
  tech[[i]] <- list(inj_camp_zoop$technicien_1[[i]], inj_camp_zoop$technicien_2[[i]])
} # Chaque niveau de la liste correspond à une association des deux noms des technicien/ne/s pour chaque ligne du tableau

inj_camp_zoop$technicians <- tech # Ajout de la liste au tableau à injecter dans Coléo
```

#### 8.1.5. On renseigne le type de campagnes, ici **zooplancton**. Prenez garde à bien conserver la même orthographe.

```r
inj_camp_zoop$type <- "zooplancton"
```

#### 8.1.6. On tansforme le tableau en liste afin de pouvoir l'injecter dans Coléo.

```r
camp_ls <- apply(inj_camp_zoop,1,as.list)
str(camp_ls)
```
#### 8.1.7. Il est maintenant possible de procéder à l'injection.

```r
COLEO_camp_inj <- post_campaigns(camp_ls)
```
La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

### 8.2. Injections des repères associés aux nouvelles campagnes

Les champs qui peuvent être remplis dans Coléo sont les suivants (les champs en gras sont obligatoires) :

* **campaign_id** : doit matcher avec site_code/site_id & opened_at
* **geom**

#### 8.2.1. On commence par séléctionner les champs d'interêts & on matche les noms de variables avec celles de Coléo.

```r
inj_land_zoop <- dplyr::select(camp_zoopl, site_code=no_de_reference_du_site, opened_at=date_debut, lat=latitude, lon = longitude)
```

#### 8.2.2. On récupère le `site_id`, nécessaire à l'injection.

```r
inj_land_zoop <- dplyr::left_join(inj_land_zoop, sites[, c(1, 4)], by = "site_code")
names(inj_land_zoop)[5] <- "site_id"
```

#### 8.2.3. On récupère le `campaign_id`, nécessaire à l'injection.

```r
inj_land_zoop$opened_at <- as.character(inj_land_zoop$opened_at)
inj_land_zoop <- dplyr::left_join(inj_land_zoop, camp[, c(1, 2, 5)], by = c("site_id", "opened_at"))
names(inj_land_zoop)[6] <- "campaign_id"
```

#### 8.2.4. On garde une ligne par repère (c'est-à-dire par campagne).

```r
inj_land_zoop <- inj_land_zoop[!duplicated(inj_land_zoop),]
```

#### 8.2.5. On transforme le tableau en liste pour pouvoir l'injecter dans Coléo.

```r
land_ls <- apply(inj_land_zoop,1,as.list)
str(land_ls)
```

#### 8.2.6. On créé le champs `geom` de COLEO, sous forme de liste, en utilisant les variables *lat* & *lon* du tableau.

```r
geom <- apply(inj_land_zoop,1, function(x){
if(!any(is.na(x["lat"]),is.na(x["lon"]))){
  return(geojsonio::geojson_list(as.numeric(c(x["lon"],x["lat"])))$features[[1]]$geometry)
} else {
  return(NA)
}})
```

#### 8.2.7. On fusionne les deux listes en prévision de l'injection dans Coléo.

```r
for(i in 1:length(land_ls)){
 land_ls[[i]]$geom <- geom[i][[1]]
 if(is.list(land_ls[[i]]$geom)){
   land_ls[[i]]$geom$crs <- list(type="name",properties=list(name="EPSG:4326"))
 }
}
```
La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

#### 8.2.7. Il est maintenant possible de procéder à l'injection.

```r
COLEO_land_inj <- post_landmarks(land_ls)
```

### 8.3. Injections des observations associées aux nouvelles campagnes

Les champs qui peuvent être remplis dans Coléo sont les suivants (les champs en gras sont obligatoires) :

* **date_obs** : date_debut
* **is_valid** : par défaut = 1
* **campaign_id** : récupération avec site_id et opened_at(=date_obs)
* *campaign_info*
* *time_obs*
* *stratum*
* *axis*
* *distance*
* *distance_unit*
* *depth* : Profondeur_m
* *sample_id*
* *thermograph_id*
* *notes* : Date_denombrement + Taxonomiste


#### 8.3.1. On séléctionne les champs d'interêts & on matche les noms de variables avec celles de Coléo.

```r
inj_obs_zoop <- dplyr::select(camp_zoopl, site_code=no_de_reference_du_site, opened_at=date_debut, depth = Profondeur_m)
inj_obs_zoop$is_valid <- 1
inj_obs_zoop$notes <- paste0(camp_zoopl$Taxonomiste, "Date_denombrement", camp_zoopl$Date_denombrement, sep = "-")
```

#### 8.3.2. On récupère le `site_id`, néceesaire à l'injection.

```r
inj_obs_zoop <- dplyr::left_join(inj_obs_zoop, sites[, c(1, 4)], by = "site_code")
names(inj_obs_zoop)[6] <- "site_id"
```

#### 8.3.3. On récupère le `campaign_id`, nécessaire à l'injection.

```r
inj_obs_zoop$opened_at <- as.character(inj_obs_zoop$opened_at)
inj_obs_zoop <- dplyr::left_join(inj_obs_zoop, camp[, c(1, 2, 5)], by = c("site_id", "opened_at"))
names(inj_obs_zoop)[7] <- "campaign_id"
```

#### 8.3.4. On modifie le nom pour la date d'observation.

```r
names(inj_obs_zoop)[2] <- "date_obs"
```

#### 8.3.5. On conserve les lignes uniques du jeu de données.

```r
inj_obs_zoop <- inj_obs_zoop[!duplicated(inj_obs_zoop),]
```

#### 8.3.6. On transforme le tableau en liste pour l'injection dans Coléo.

```r
obs_ls <- apply(inj_obs_zoop,1,as.list)
```

#### 8.3.7. Il est maintenant possible de procéder à l'injection.

```r
COLEO_obs_inj <- post_observations(obs_ls)
```
La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

### 8.4. Injections de l'abondance des espèces associées aux nouvelles campagnes

Les champs qui peuvent être remplis dans Coléo sont les suivants (les champs en gras sont obligatoires) :

* **taxa_name** : nom_scientifique
* **variable** : "abondance"
* **observation_id** : à récupérer avec site_id --> site_code --> campaign_id + opened_at
* *value* : abondance

#### 8.4.1. On séléctionne les champs d'interêts & on matche les noms de variables avec celles de Coléo.

```r
inj_data_zoop <- dplyr::select(camp_zoopl, site_code=no_de_reference_du_site, opened_at=date_debut, taxa_name = nom_scientifique, value = abondance)
inj_data_zoop$variable <- "abondance"
```

#### 8.4.2. On récupère le `site_id`, nécessaire à l'injection.

```r
inj_data_zoop <- dplyr::left_join(inj_data_zoop, sites[, c(1, 4)], by = "site_code")
names(inj_data_zoop)[6] <- "site_id"
```

#### 8.4.3. On récupère le `campaign_id`, nécessaire à l'injection.

```r
inj_data_zoop$opened_at <- as.character(inj_data_zoop$opened_at)
inj_data_zoop <- dplyr::left_join(inj_data_zoop, camp[, c(1, 2, 5)], by = c("site_id", "opened_at"))
names(inj_data_zoop)[7] <- "campaign_id"
```

#### 8.4.4. On récupère le `observation_id`, nécessaire à l'injection.

```r
names(inj_data_zoop)[2] <- "date_obs"
inj_data_zoop <- dplyr::left_join(inj_data_zoop, obs[, c(1, 2, 12)], by = c("campaign_id", "date_obs"))
names(inj_data_zoop)[8] <- "observation_id"
```

#### 8.4.5. On transforme le jeu de données en liste pour l'injection dans Coléo.

```r
data_ls <- apply(inj_data_zoop,1,as.list)
```

#### 8.4.6. Il est maintenant possible de procéder à l'injection.

```r
COLEO_data_inj <- postpost_obs_species(data_ls) # Fonctionnel

```
La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Bravo ! Vous venez de terminer les étapes d'injections des campagnes **zooplancton** ! Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).
