---
title: "Tutoriel pour injection des campagnes chiroptères/chauves-souris"
author: "Guillaume Larocque"
date: "24 février 2021"
output: 
  html_document
---

```{=html}
<style>
div.red { background-color:#ff0000; border-radius: 8px; padding: 5px;}
</style>
```
```{=html}
<style>
div.blue { background-color:#e6f0ff; border-radius: 8px; padding: 5px;}
</style>
```
::: {.red}
Vignette en cours de développement
:::

## 1. Créer une base de données excel

Afin d'injecter des nouvelles campagnes faisant l'inventaire des papillons, il vous faut créer un fichier excel avec les colonnes suivantes :

+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| Variable          | Description                                                                                                                                                                                   |
+===================+===============================================================================================================================================================================================+
| *cell_code*       | code numérique unique pour chaque cellule                                                                                                                                                     |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *site_code*       | code alpha-numérique unique du site                                                                                                                                                           |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **habitat_type**  | type d'habitat dans lequel la campagne a été effectuée - `lac`, `rivière`, `forestier`, `marais`, `marais côtier`, `toundrique`, `tourbière`                                                  |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *lat*             | latitude du site d'échantillonnage                                                                                                                                                            |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *lon*             | longitude du site d'échantillonnage                                                                                                                                                           |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **opened_at**     | date du début de la campagne au format `YYYY-MM-DD`                                                                                                                                           |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *closed_at*       | date de la fin de la campagne au format `YYYY-MM-DD`                                                                                                                                          |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *mic_ultra_code*  | Code de l'appareil ultrason utilisé                                                                                                                                                           |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *mic_h\_cm_ultra* | Hauteur de l'appareil ultrason utlisé (cm)                                                                                                                                                    |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *technician_1*    |                                                                                                                                                                                               |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *technician_2*    |                                                                                                                                                                                               |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *date_obs*        | DATE OF OBSERVATION `YYYY-MM-DD`                                                                                                                                                              |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *time_obs*        | TIME OF OBSERVATION `HH:MM:SS` HOURS AS 24 H, LEADING ZEROS SO ALWAYS SAME VALUES                                                                                                             |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *vernacular_fr*   | nom commun français des espèces observées                                                                                                                                                     |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *taxa_name*       | nom latin des espèces observées                                                                                                                                                               |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **rank**          | rang taxonomique - `sous-embranchement`, `embranchement`, `sous-classe`, `classe`, `sous-ordre`, `ordre`, `super-famille`, `famille`, `genre`, `espèce`, `sous-espèce`, `variété`, `complexe` |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **category**      | categorie d'organisme vivant - `poissons`, `plantes`, `oiseaux`, `amphibiens`, `arthropodes`, `mammifères`, `reptiles`, `autres`, `mollusques`                                                |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *tsn*             | identifiant ITS (TSN)                                                                                                                                                                         |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| *note*            |                                                                                                                                                                                               |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
|                   |                                                                                                                                                                                               |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| campaign\_*type*  | type de campagne - `acoustique`                                                                                                                                                               |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+

Prenez soin de :

-   vérifier les **variables en gras** car elles possèdent des valeurs prédéfinies dans Coléo. Toutes les valeurs dans votre fichier doivent correspondre à une des valeurs possibles (vérifiez les majuscule, les accents ou d'éventuelles espaces inutiles).
-   ne pas laisser de case vide. Inscrivez *NA* lorsque nécessaire.
-   vérifier que votre fichier ne contienne que des nouvelles campagnes.
-   vérifier l'encodage de votre fichier qui doit correspondre à "UTF-8".

```{r, child="etape2_to_7.Rmd"}
```

## 8. Injection des campagnes de chiroptères

Pour une injection complète d'une campagne, il est nécessaire de passer par l'importation d'informations successives dans différentes tables de Coléo. La hiérarchie des tables à renseigner est cruciale, sans quoi l'injection de la campagne est vouée à l'échec. Les prochaines étapes détaillent l'ajout d'information dans les tables:

1.  Campagnes ("*/campaigns*")
2.  Appareils ("*/devices*")
3.  Repères ("\*/landmarks"))
4.  Observations ("*/observations*")
5.  Observations des espèces ("*/obs_species*")

### 8.1. Injections des informations sur les nouvelles campagnes

Les champs de la table **campagnes** ("/campaigns") de Coléo qui seront remplis sont les suivants :

-   *site_id*
-   *type*: type de la campagne
-   *technicians*: liste composée de "technician_1" et "technician_2"
-   *opened_at*
-   *closed_at*

#### 8.1.1. On commence par séléctionner les champs d'interêts.

``` {.r}
# 8.1.1. Sélection
donnees_inj_camp <- dplyr::select(donnees_inj_cell_site_id,
                           site_id,
                           type,
                           technician_1,
                           technician_2,
                           opened_at,
                           closed_at) |>
  # 8.1.2. Retrait des duplicat
  distinct
```

#### 8.1.2. On garde une ligne unique par nouvelle campagne.

avec `distinct()`, en haut

#### 8.1.3. On créé la liste pour le nom des techniciens.

``` {.r}
# 8.1.3. Création liste de technicien.ne.s

donnees_inj_camp_tech <- donnees_inj_camp |>
  mutate(technicians = map(technician_1, ~ list(.x))) |>
  select(-technician_1)

# Chaque niveau de la liste correspond à une association des deux noms des technicien/ne/s pour chaque ligne du tableau
```

#### 8.1.4. On transforme le tableau en liste pour pouvoir injecter les données dans Coléo.

``` {.r}
# 8.1.4. Conversion de l'objet pour l'injection
camp_ls <- transpose(donnees_inj_camp_tech)
```

#### 8.1.5. On injecte.

``` {.r}
# 8.1.5. Injection
COLEO_camp_inj <- rcoleo::post_campaigns(camp_ls) 
```

La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

#### 8.1.6. On récupère la liste de campagnes provenant de Coléo.

``` {.r}
# 8.1.6. Liste des campagnes
campaigns <- rcoleo::get_campaigns()

campaigns_df <- bind_rows(campaigns[[1]]$body)
```

#### 8.1.7. On récupère le id unique pour chaque campagne nouvellement insérées.

``` {.r}
# 8.1.7. Récupération des IDs des campagnes
donnees_inj_cell_site_camp_id <- left_join(donnees_inj_cell_site_id,
                                      campaigns_df |>
                                        select(campaign_id = id,
                                               site_id,
                                               opened_at, 
                                               type),
                                      by = c("site_id", "opened_at", "type"))
```

### 8.2. Injections des repères associés aux nouvelles campagnes

Les champs de la table **repères** ("/landmarks") de Coléo qui peuvent être remplis sont les suivants : \* *campaign_id* \* *geom*

#### On commence par séléctionner les champs d'interêts.

``` {.r}
# 8.2.1. Sélection
land_camp <- dplyr::select(donnees_inj_cell_site_camp_id,
                           campaign_id,
                           lat,
                           lon) |>
  # 8.2.2. Retrait des duplicats
  distinct
```

On garde une ligne par repère (c'est-à-dire par campagne), avec `distinct`

#### On créé le champs `geom` de Coléo, sous forme de liste, en utilisant les variables *lat* & *lon* du tableau.

``` {.r}
# 8.2.4. Création de la variable `geom`
land_camp_formatted <- rcoleo::format_spatial(land_camp)
```

#### On transforme le tableau en liste pour pouvoir l'injecter dans Coléo.

``` {.r}
# 8.2.3. Conversion de l'objet pour l'injection
land_ls <- land_camp_formatted |>
  select(campaign_id, geom) |>
  transpose
```

#### Il est maintenant possible de procéder à l'injection.

``` {.r}
# 8.2.6. Injection
COLEO_land_inj <- rcoleo::post_landmarks(land_ls)
```

La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

### 8.3. Injections des appareils

Les champs de la table **appareils** ("/devices") de Coléo qui peuvent être remplis sont les suivants :

-   *campaign_id*
-   *mic_ultra_code*
-   *mic_h\_cm_ultra*

#### 8.3.1. On commence par séléctionner les champs d'interêts.

``` {.r}
# 8.3.1. Sélection
app_camp <- dplyr::select(donnees_inj_cell_site_camp_id,
                          campaign_id,
                          mic_ultra_code) |>
  mutate(mic_h_cm_ultra = NULL) |>
  distinct

app_camp_ls <- transpose(app_camp)
```

#### 8.3.4. On injecte.

``` {.r}
# 8.3.4. Injection
COLEO_app_inj <- rcoleo::post_environments(app_camp_ls)
```

La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

### 8.5. Insertion des observations

Les champs de la table **observations** ("/observations") de Coléo qui peuvent être remplis sont les suivants :

-   *campaign_id*
-   *is_valid* : 1 par défaut
-   *date_obs*

#### 8.5.1. On sélectionne les champs d'intérêts.

``` {.r}
# 8.5.1. Création & sélection
# Création de 2 variables nécessaires
camp$date_obs <- camp$opened_at
camp$is_valid <- 1 # valeur de 1 par défaut

# On sélectionne les champs d'intérêts.
obs_camp <- dplyr::select(donnees_inj_cell_site_camp_id,
                          date_obs,
                          time_obs,
                          # note column s'il y en a
                          notes = NULL,
                          campaign_id) |>
  mutate(is_valid = 1)
```

#### 8.5.2. On garde une ligne par campagne & on formatte les données à insérer.

``` {.r}
# 8.5.2. Retrait des duplicats
obs_camp_ls <- obs_camp |>
  distinct |>
  transpose
```

#### 8.5.3. On injecte.

``` {.r}
# 8.5.4. Injection
COLEO_obs_inj <- rcoleo::post_obs(obs_camp_ls)
```

La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

#### 8.5.5. On récupère la liste des observations de Coléo et on met à jour le tableau de campagnes à injecter.

``` {.r}
# 8.5.5. Acquisition de la liste d'observations de Coléo
obs <- rcoleo::get_gen("/observations")
obs <- do.call(plyr::rbind.fill, obs$body)

# Mise à jour des données à injecter avec l'observation_id
camp <- dplyr::left_join(camp, obs[, c("id", "campaign_id", "date_obs")], by = c("campaign_id", "date_obs"))
names(camp)[names(camp) == "id"] <- "observation_id"
```

### 8.6. Injections des observations d'espèce

Les champs de la table **observations des espèces** ("/obs_species") de Coléo qui peuvent être remplis sont les suivants :

-   *observation_id*
-   *taxa_name* : nom latin de l'espèce
-   *variable*
-   *value*

#### 8.6.1. On sélectionne les champs d'intérêts.

``` {.r}
# 8.6.1. Sélection
obs_spe_camp <- dplyr::select(camp
                              observation_id,
                              value = abondance,
                              taxa_name)

# Ajout d'une variable
obs_spe_camp$variable <- "abondance"
```

#### 8.6.2. On formatte les données à injecter.

``` {.r}
# 8.6.2. Conversion de l'objet pour l'injection
obs_spe_camp_ls <- apply(obs_spe_camp, 1, as.list)
```

#### 8.6.3. On injecte.

``` {.r}
# 8.6.3. Injection
COLEO_obsref_inj <- rcoleo::post_obs_species(obs_spe_camp_ls)
```

La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Bravo ! Vous venez de terminer les étapes d'injections des campagnes **papilonidés** ! Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).
