---
title: "Tutoriel pour injection des campagnes odonate"
author: "Claire-Cécile Juhasz"
date: "12 novembre 2020"
output: 
  html_document
---
<style>
div.red { background-color:#ff0000; border-radius: 8px; padding: 5px;}
</style>

<style>
div.blue { background-color:#e6f0ff; border-radius: 8px; padding: 5px;}
</style>

<div class = "red">

Vignette en cours de développement

</div>

## 1. Créer une base de données excel

  Afin d'injecter des nouvelles campagnes *papillon* dans la base de données Coléo, vous devez regrouper les informations suivantes dans un fichier excel :

|Variable|Description                      |
|--------|--------------------------------------------------------------------------|
|*cell_code*|code numérique unique pour chaque cellule|
|*site_code*|code alpha-numérique unique du site|
|**type_hab**|type d'habitat dans lequel la campagne a été effectuée - `lac`, `rivière`, `forestier`, `marais`, `marais côtier`, `toundrique`, `tourbière`|
|*nom_lac*||
|*lat*|latitude du site d'échantillonnage|
|*lon*|longitude du site d'échantillonnage|
|*opened_at*|date du début du prélèvement au format `YYYY-MM-DD`|
|*closed_at*|date de la fin du prélèvement au format `YYYY-MM-DD`|
|*technician_1*||
|*technician_2*||
|*time_start*|heure du début de la campagne|
|*time_finish*|heure de la fin de la campagne|
|*temp_c*|température en degré celsius|
|**type**|type de campagne - `odonates`|
|**sky**| variable numérique symbolisant l'état du ciel, 1 = `dégagé (0 à 10 %)`, 2 = `partiellement nuageux (10 à 50 %)`, 3 = `nuageux (50 à 90 %)`, 4 = `pluvieux`, 5 = `orageux`|
|**wind**| variable numérique symbolisant le niveau d'intensité du vent, 1 = `calme (moins de 1 km/h)`, 2 = `très légère brise (1 à 5 km/h)`, 3 = `légère brise (6 à 11 km/h)`, 4 = `petite brise (12 à 19 km/h)`, 5 = `jolie brise (20 à 28 km/h)`|
|*vernacular_fr*|nom commun français des espèces observées|
|*taxa_name*|nom latin des espèces observées|
|*abondance*|valeur d'abondance de l'espèce observée|
|*note*||
|||

Prenez soin de :

* vérifier les **variables en gras** car elles possèdent des valeurs prédéfinies dans Coléo. Toutes les valeurs dans votre fichier doivent correspondre à une des valeurs possibles (vérifiez les majuscule, les accents ou d'éventuelles espaces inutiles).
* ne pas laisser de case vide. Inscrivez *NA* lorsque nécessaire.
* vérifier que votre fichier ne contienne que des nouvelles campagnes.
* vérifier l'encodage de votre fichier qui doit correspondre à "UTF-8".


```{r, child="etape2_to_7.Rmd"}
```


## 8. Injection des campagnes d'odonates
Pour une injection complète d'une campagne, il est nécessaire de passer par l'importation d'informations successives dans différentes tables de Coléo. La hiérarchie des tables à renseigner est cruciale, sans quoi l'injection de la campagne est vouée à l'échec. Les prochaines étapes détaillent l'ajout d'information dans les tables:

1. Campagnes ("*/campaigns*")
2. Repères ("*/landmarks*")
3. Environnements ("*/environments*")
4. Efforts ("*/efforts*")
5. Observations ("*/observations*")
6. Observations des espèces ("*/obs_species*")

### 8.1. Injections des informations sur les nouvelles campagnes

Les champs de la table **campagnes** ("/campaigns") de Coléo qui seront remplis sont les suivants :

* *site_id*
* *type*: type de la campagne
* *technicians*: liste composée de `technician_1` et `technician_2`
* *opened_at*
* *closed_at*

#### 8.1.1. On commence par séléctionner les champs d'interêts.

```r
# 8.1.1. Sélection
camp_camp <- dplyr::select(camp,
                          site_id,
                          type,
                          technician_1,
                          technician_2,
                          opened_at,
                          closed_at)
```

#### 8.1.2. On garde une ligne unique par nouvelle campagne.

```r
# 8.1.2. Retrait des duplicat
camp_camp <- camp_camp[!duplicated(camp_camp),]
```

#### 8.1.3. On créé la liste pour le nom des techniciens.

```r
# 8.1.3. Création liste de technicien.ne.s
tech <- list() # Création d'un objet `list` vide

for(i in 1:length(camp_camp$site_id)){

  tech[[i]] <- list(camp_camp$technician_1[[i]], camp_camp$technician_2[[i]])
  
} # Chaque niveau de la liste correspond à une association des deux noms des technicien/ne/s pour chaque ligne du tableau

camp_camp$technicians <- tech # Ajout de la liste au tableau à injecter dans Coléo
```


#### 8.1.4. On transforme le tableau en liste pour pouvoir injecter les données dans Coléo.

```r
# 8.1.4. Conversion de l'objet pour l'injection
camp_ls <- apply(camp_camp, 1, as.list)
```

#### 8.1.5. On injecte.

```r
# 8.1.5. Injection
COLEO_camp_inj <- rcoleo::post_campaigns(camp_ls) 
```
La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

#### 8.1.6. On récupère la liste de campagnes provenant de Coléo.

```r
# 8.1.6. Liste des campagnes
campaigns <- rcoleo::get_campaigns()
campaigns <- do.call(rbind.fill, campaigns[[1]]$body)
```
#### 8.1.7. On récupère le id unique pour chaque campagne nouvellement insérées.

```r
# 8.1.7. Récupération des IDs des campagnes
camp <- dplyr::left_join(camp,
                         campaigns[, c("id", "site_id", "opened_at", "type")],
                         by = c("site_id", "opened_at", "type"))
                         
names(camp)[names(camp) == "id"] <- "campaign_id"

```

### 8.2. Injections des repères associés aux nouvelles campagnes

Les champs de la table **repères** ("/landmarks") de Coléo  qui peuvent être remplis sont les suivants :

* *campaign_id*
* *geom* : créé à partir des variables `lat` & `lon`

#### 8.2.1. On commence par séléctionner les champs d'interêts.
```r
# 8.2.1. Sélection
land_camp <- dplyr::select(camp,
                           campaign_id,
                           lat,
                           lon)
```
#### 8.2.2. On garde une ligne par repère (c'est-à-dire par campagne).

```r
# 8.2.2. Retrait des duplicats
land_camp <- land_camp[!duplicated(land_camp),]
```

#### 8.2.3. On transforme le tableau en liste pour pouvoir l'injecter dans Coléo.

```r
# 8.2.3. Conversion de l'objet pour l'injection
land_ls <- apply(land_camp, 1, as.list)
```

#### 8.2.4. On créé le champs `geom` de Coléo, sous forme de liste, en utilisant les variables `lat` & `lon` du tableau.

```r
# 8.2.4. Création de la variable `geom`
geom <- apply(land_camp, 1, function(x){

if(!any(is.na(x["lat"]),is.na(x["lon"]))){

  return(geojsonio::geojson_list(as.numeric(c(x["lon"],x["lat"])))$features[[1]]$geometry)
  
} else {

  return(NA)
  
}})
```

#### 8.2.5. On fusionne les deux listes en prévision de l'injection dans Coléo.

```r
# 8.2.5. Fusion des listes
for(i in 1:length(land_ls)){

 land_ls[[i]]$geom <- geom[i][[1]]
 
 if(is.list(land_ls[[i]]$geom)){
 
   land_ls[[i]]$geom$crs <- list(type = "name", properties = list(name = "EPSG:4326"))
 }
}
```
#### 8.2.6. Il est maintenant possible de procéder à l'injection.

```r
# 8.2.6. Injection
COLEO_land_inj <- post_landmarks(land_ls)
```
La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

### 8.3. Injections des caractéristiques environnementales

Les champs de la table **environnement** ("/environment") de Coléo qui peuvent être remplis sont les suivants :

* *campaign_id*
* *wind*
* *sky*
* *temp_c*

<div class = "blue">

**Rappel** - Les entrées pour les variables `wind` et `sky` doivent parfaitement correspondre à ce qui est attendu par la base de données Coléo.

</div>

#### 8.3.1. On commence par séléctionner les champs d’interêts.

```r
# 8.3.1. Sélection
env_camp <- select(camp,
                  campaign_id,
                  wind,
                  sky,
                  temp_c)
```

#### 8.3.2. On garde une ligne par campagne.

```r
# 8.3.2. Retrait des duplicats
env_camp <- env_camp[!duplicated(env_camp),]
```

#### 8.3.3. On transforme en liste.

```r
# 8.3.3. Conversion de l'objet pour l'injection
env_camp_ls <- apply(env_camp, 1, as.list)
```

#### 8.3.4. On injecte.

```r
# 8.3.4. Injection
COLEO_env_inj <- rcoleo::post_environments(env_camp_ls)
```

La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

### 8.4. Injections des efforts

Les champs de la table **efforts** ("/efforts") de Coléo qui peuvent être remplis sont les suivants :

* *campaign_id*
* *time_start*
* *time_finish*

#### 8.4.1. On sélectionne les champs d'intérêts.

```r
# 8.4.1. Sélection
eff_camp <- select(camp,
                   campaign_id,
                   time_start,
                   time_finish)
```

#### 8.4.2. On garde une ligne par campagne.

```r
# 8.4.2. Retrait des duplicats
eff_camp <- eff_camp[!duplicated(eff_camp),]
```

#### 8.4.3. On transforme en liste.

```r
# 8.4.3. Conversion de l'objet pour l'injection
eff_camp_ls <- apply(eff_camp, 1, as.list)
```
#### 8.4.4. On injecte.

```r
# 8.4.4. Injection
COLEO_eff_inj <- rcoleo::post_efforts(eff_camp_ls) 
```

La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

### 8.5. Insertion des observations

Les champs de la table **observations** ("/observations") de Coléo qui peuvent être remplis sont les suivants :

* *campaign_id*
* *is_valid* : 1 par défaut
* *date_obs*

#### 8.5.1. On sélectionne les champs d'intérêts.

```r
# 8.5.1. Création & sélection
# Création de 2 variables nécessaires
camp$date_obs <- camp$opened_at
camp$is_valid <- 1 # valeur de 1 par défaut

# Sélection des champs d'intérêts
obs_camp <- select(camp,
                   date_obs,
                   is_valid,
                   notes = note,
                   campaign_id)
```

#### 8.5.2. On garde une ligne par campagne.

```r
# 8.5.2. Retrait des duplicats
obs_camp <- obs_camp[!duplicated(obs_camp),]
```

#### 8.5.3. On formatte les données à insérer.

```r
# 8.5.3. Conversion de l'objet pour l'insertion
obs_camp_ls <- apply(obs_camp, 1, as.list)
```

#### 8.5.4. On injecte.

```r
# 8.5.4. Injection
COLEO_obs_inj <- rcoleo::post_obs(obs_camp_ls)
```

La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).

#### 8.5.5. On récupère la liste des observations de Coléo et on met à jour le tableau de campagnes à injecter.

```r
# 8.5.5. Acquisition de la liste d'observations de Coléo
obs <- rcoleo::get_gen("/observations")
obs <- do.call(rbind.fill, obs$body)

# Mise à jour des données à injecter avec l'observation_id
camp <- dplyr::left_join(camp,
                         obs[, c("id", "campaign_id", "date_obs")],
                         by = c("campaign_id", "date_obs"))
names(camp)[names(camp) == "id"] <- "observation_id"
```

### 8.6. Injections des observations d'espèce

Les champs de la table **observations des espèces** ("/obs_species") de Coléo  qui peuvent être remplis sont les suivants :

* *observation_id*
* *taxa_name* : nom latin de l'espèce
* *variable*
* *value*

#### 8.6.1. On sélectionne les champs d'intérêts.

```r
# 8.6.1. Sélection
obs_spe_camp <- select(camp,
                      observation_id,
                      value = abondance,
                      taxa_name)

# Ajout d'une variable
obs_spe_camp$variable <- "abondance"
```

#### 8.6.2. On formatte les données à injecter.

```r
# 8.6.2. Conversion de l'objet pour l'injection
obs_spe_camp_ls <- apply(obs_spe_camp, 1, as.list)
```

#### 8.6.3. On injecte.

```r
# 8.6.3. Injection
COLEO_obsref_inj <- rcoleo::post_obs_species(obs_spe_camp_ls)
```
La sortie R vous informe sur le déroulement de l'insertion. Le message `Good job ! Toutes les insertions ont été créées dans COLEO` indique que les informations ont bien été enregistrées dans Coléo. Bravo ! Vous venez de terminer les étapes d'injections des campagnes **odonates** ! Dans le cas inverse, le message `Oups... un problème est survenu` apparait, suivi des codes de statut pour chaque requête d'injections (pour plus d'informations à propos des [codes de statut](https://http.cat/)).
