---
output: html_document
---

## 2. Corriger la base de données

Il est très important de s'assurer que la base de données excel soit sans erreur **avant** de l'injecter dans Coléo. Coléo n'a pas de système de correction et va prendre toutes les entrées, même si elles contiennent des erreurs.

## 3. Créer un projet R

Dans RStudio,

-   Aller dans `File` \> `New Project` \> `New Directory` \> `New Project`
-   Choisir un nom de projet et un lieu dans les fichiers pour le projet

Les projets permettent de travailler dans un répertoire de travail (*working directory*). La base de données doit donc être sauvegardée dans le même dossier que le projet afin de faire parti du répertoire de travail.

## 4. Sauvegarder la base de données en format .csv dans le même dossier que le projet R

::: {.blue}
**Rappel** - L'encodage du fichier .csv doit être en "UTF-8"
:::

## 5. Installer et charger les packages nécessaires

S'il ne s'agit pas de vos premières injections dans Coléo avec R, vous pouvez directement passer à l'**étape 5.2**. Sinon vous devez installer les packages nécessaires.

### 5.1. Installation des packages

Dans RStudio :

``` {.r}
# 5.1. Installation des packages
install.packages("devtools")
install.packages("dplyr")
install.packages("geojsonio")
install.packages("readr")
```

Pour installer le package `rcoleo`, il faut utiliser le package `` remotes, il faut donc l'appeller avec ` ``library()\`

``` {.r}
# Chargement de devtools
library(remotes)
# Installation du package rcoleo à partir de github
install_github("ReseauBiodiversiteQuebec/rcoleo") 
```

### 5.2. Chargement des packages

``` {.r}
# 5.2. Chargement des packages
library(rcoleo)
library(dplyr)
library(geojsonio)
library(readr)
```

## 6. Mise en cache son jeton d'accès

Ce jeton permet d'apporter des modifications dans Coléo. Il est unique et se retrouve dans Coléo, sous le profil de l'utilisateur dans le menu à gauche.

``` {.r}
# 6. Mise en cache son jeton d'accès
saveRDS("votrejeton",".httr-oauth")
```

Cette étape n'est faite qu'une fois et permet l'enregistrement de votre jeton dans le répertoire du projet R. Une fois faite, elle est supprimée du code d'injection. Le jeton est confidentiel.

## 7. Télécharger des données de Coléo

data = coleo_request_general("cells", response_as_df = TRUE, cell_code = "105_101")