---
title: "Injection des espèces de référence dans Coléo"
author:
  - "Joelle Spooner"
  - "Andrew MacDonald"
output: rmarkdown::html_vignette
---


## 1. Créer une base de données excel
Les colonnes de ce fichier excel doivent être les suivantes

* **name**: les noms latins de chacune des espèces/famille/genre/..., ex. Plebejus idas
* **vernacular_fr**: le nom français associé au nom latin, sans majuscule et avec les accents, ex. martre d'amérique
* **rank**: le rang taxonomique, les options sont: 'sous-embranchement', 'embranchement', 'sous-classe', 'classe', 'sous-ordre', 'ordre', 'super-famille', 'famille', 'genre', 'espèce', 'sous-espèce'
* **category**: la catégorie d'organisme vivant, les options sont: 'poissons','plantes','oiseaux','amphibiens','arthropodes','mammifères','reptiles','autres','mollusques'
* **tsn**: Taxonomic serial number (TSN) fournis par ITIS
* **vascan_id**: NA si l'organisme vivant n'est pas une plante, si l'organisme vivant est une plante: entrer son numéro d'identifiant vascan
* **bryoquel_id**: NA si l'organisme vivant n'est pas un bryophyte, si l'organisme vivant est un bryophyte: entrer son numéro d'identifiant bryoquel
* **created_at**: y écrire la date du jour sous le format AAAA-MM-JJ
* **updated_at**: y écrire la date du jour sous le format AAAA-MM-JJ

Note:

* ne pas laisser de case vide, inscrire NA lorsque nécessaire
* si vous avez des colonnes supplémentaires dans votre base de données, ex. nom anglais et commentaires, voir l'étape 7.8 pour qu'elles ne soient pas prises en compte lors de l'injection

```{r, child="etape2_to_7.Rmd"}
```


## 7. Injection des taxons de référence dans Coléo

* **7.1** Cette étape appelle les packages installés afin qu'ils puissent être utilisés

```r
library(rcoleo)
library(dplyr)
```
* **7.2** L'étape suivante permet d'extraire la liste d'espèces déjà sur Coléo

```r
taxa_list <- get_species()

str(taxa_list, max.level = 3)

all_things <- dplyr::bind_rows(taxa_list[[1]]$body)
```
* **7.3** Cette étape permet d'intégrer les données de la base de données des organismes vivants à ajouter à Coléo

```r
corrections <- read.csv("./lenomdevotrebasededonnées.csv", header = TRUE, sep = ',', stringsAsFactors = FALSE, encoding = "UTF-8") #l'encoding UTF-8 permet de garder les accents
```

```r
corrections <- read.csv("./corrections_liste_sp_JS.csv", header = TRUE, sep = ',', stringsAsFactors = FALSE, encoding = "UTF-8")
```
si votre ordinateur est en français, le séparateur de votre base de données pourrait être un ; dans ce cas, changer sep = ',' pour sep = ';' dans l'argument ci-haut



* **7.4** Cette étape permet de s'assurer que les noms de colonnes sont les mêmes dans Coléo que dans votre base de données

```r
glimpse(all_things)
glimpse(corrections)
```
* **7.4.1** Étape facultative, elle permet de changer des noms de colonnes si ils ne sont pas écrits de la même façon que Coléo. Comme dans l'exemple ci-haut, la colonne name du fichier de corrections est écrite X.U.FEFF.name, ce qui n'est pas adéquat.

```r
names(corrections)[1] <- "name"
```
* **7.5** Cette étape permet de visualiser quelles entrées de la base de données se retrouvent déjà dans Coléo en fonction du nom latin. Elle permet donc d'éviter les répétitions d'entrées.

```r
semi_join(corrections, all_things, by = "name")
```
* **7.6** En lien avec l'étape précédente, celle-ci permet de sélectionner toutes les entrées qui ne se trouvent pas dans Coléo en fonction du nom latin afin d'éviter les répétitions.

```r
correctionsuniques <- anti_join(corrections, all_things, by = "name")
```

* **7.8** Cette étape est seulement nécessaire si la base de données comprend des colonnes qui ne sont pas dans Coléo, ou si les colonnes tsn et/ou bryoquel comprennent des valeurs NA

```r
correctionscol <- select(correctionsuniques, name, vernacular_fr, rank, category, tsn, vascan_id, bryoquel_id, created_at, updated_at)
```

Note: L'injection ne fonctionnera pas pour les entrées avec des valeurs de tsn et/ou bryoquel de NA. Après avoir injecté toutes les espèces qui ont un tsn et/ou bryoquel, enlever tsn et/ou bryoquel de la fonction si haut. De cette façon, l'injection se fera sans le tsn/bryoquel_id pour les espèces qui n'en ont pas.

* **7.9** Transposer le dataframe afin de l'injecter

```r
correctionstoupload <- purrr::transpose(correctionscol)
```

**Cette dernière étape injecte les données de la base de données dans Coléo**

```r
rcoleo:::post_species(correctionstoupload)
```

fini!

