---
title: "Injection de nouveaux sites dans Coléo"
author: "Claire-Cécile Juhasz"
output: rmarkdown::html_vignette
---


## 1. Créer une base de données excel
Les colonnes de ce fichier excel doivent correspondrent aux champs contenus dans la base de données Coléo, qui sont les suivants:  
  
* **cell_id** : indispensable - numéro unique de chaque cellule - peut-être récupéré à l'aide de la fonction `get_cells()`
* **off_station_code_id** : facultative - **Need more information**
* **site_code** : indispensable - code alpha-numérique unique pour chaque site
* **type** : indispensable - type d'habitat où se situe le site. Les options sont : "lac", "tourbière", "forestier", "rivière", "marais", "toundrique", "marais côtier"
* **opened_at** : indispensable - date de création du site sous le format AAAA-MM-JJ
* *lat* : indispensable - latitude du site, nécessaire à la création de la varible **geom**
* *lon* : indispensable - latitude du site, nécessaire à la création de la varible **geom**
* **notes** : facultative

Note:

* ne pas laisser de case vide, inscrire NA lorsque nécessaire
* si vous avez des colonnes supplémentaires dans votre base de données, voir l'étape 7.8 pour qu'elles ne soient pas prises en compte lors de l'injection

## 2. Corriger la base de données
Il est très important de s'assurer que la base de données excel est sans erreur **avant** de l'injecter dans Coléo. Coléo n'a pas de système de correction et va prendre toutes les entrées, même si elles contiennent des erreurs. Assurez-vous également que votre base de données ne contient aucune répétition d'un même site.


## 3. Créer un projet R
Dans RStudio,

* Aller dans File > New Project > New Directory > New Project
* Choisir un nom de projet et un lieu dans les fichiers pour le projet

Les projets permettent de travailler dans un répertoire de travail. La base de données doit donc être sauvegardée dans le même dossier que le projet afin de faire parti du répertoire de travail.

## 4. Sauvegarder la base de données en format .csv dans le même dossier que le projet R

## 5. Installer les packages devtools, dplyr et rcoleo
Dans RStudio,


```r
install.packages("devtools")
install.packages("dplyr")
```
pour installer le package rcoleo, il faut utiliser le packages devtools, il faut donc l'appeller avec library()


```r
library(devtools)
install_github("RéseauBiodiversiteQuebec/rcoleo") #installe le package rcoleo à partir de github
```
## 6. Mettre en cache son jeton d'accès
Ce jeton permet d'apporter des modifications dans Coléo. Il est unique et se retrouve dans Coléo, sous le profil de l'utilisateur dans le menu à gauche.

```r
saveRDS("votrejeton",".httr-oauth")
```
Cette étape n'est faite qu'une fois et permet l'enregistrement de votre jeton dans le répertoire du projet R. Une fois faite, elle est supprimée du code d'injection. Le jeton est confidentiel.

## 7. Injection des sites dans Coléo

* **7.1** Cette étape appelle les packages installés afin qu'ils puissent être utilisés

```r
library(rcoleo)
library(dplyr)
```

```
## Warning: package 'dplyr' was built under R version 4.0.2
```
* **7.2** L'étape suivante permet d'extraire la liste des sites déjà existant dans Coléo

```r
sites_list <- get_sites()
str(sites_list, max.level = 3)
all_things <- dplyr::bind_rows(sites_list[[1]]$body)
```
* **7.3** Cette étape permet d'enregistrer un objet dans R avec les sites à ajouter dans Coléo

```r
corrections <- read.csv("./lenomdevotrebasededonnées.csv", header = TRUE, sep = ',', stringsAsFactors = FALSE, encoding = "UTF-8") #l'encoding UTF-8 permet de garder les accents
```

```r
corrections <- read.csv("./corrections_liste_sp_JS.csv", header = TRUE, sep = ',', stringsAsFactors = FALSE, encoding = "UTF-8")
```
si votre ordinateur est en français, le séparateur de votre base de données pourrait être un ; dans ce cas, changer sep = ',' pour sep = ';' dans l'argument ci-haut



* **7.4** Cette étape permet de s'assurer que les noms de colonnes sont les mêmes dans Coléo que dans votre base de données

```r
glimpse(all_things)
glimpse(corrections)
```

*NB* : À ce stade, il est normal que votre fichier "corrections" ne contienne pas la variable **geom**. Celle-ci sera créée à partir des colonnes **lat** & **lon** au cours de **l'étape 7.7**.  

* **7.4.1** Étape facultative, elle permet de changer des noms de colonnes si ils ne sont pas écrits de la même façon que Coléo. Comme dans l'exemple ci-haut, la colonne name du fichier de corrections est écrite X.U.FEFF.name, ce qui n'est pas adéquat.

```r
names(corrections) # Visualisation des noms de toutes les colonnes présentes dans votre jeu de données
names(corrections)[1] <- "name" # Sélection du premier nom ([1]) et modification de celui-ci (<- "name")
```
* **7.5** Cette étape permet de visualiser quelles entrées de la base de données se retrouvent déjà dans Coléo en fonction du code du site (**site_code**). Elle permet donc d'éviter les répétitions d'entrées.

```r
semi_join(corrections, all_things, by = "site_code")
```
* **7.6** En lien avec l'étape précédente, celle-ci permet de sélectionner toutes les entrées qui ne se trouvent pas dans Coléo en fonction du nom latin afin d'éviter les répétitions.

```r
correctionsuniques <- anti_join(corrections, all_things, by = "site_code")
```
* **7.7** Cette étape permet de créer la colonne **geom**
* **7.7.1** Conversion du dataframe en liste
```r
correctionsuniques_ls <- apply(correctionsuniques,1,as.list) # Création de la liste
str(correctionsuniques_ls) # Vérification de la structure de l'objet
```

```r
# Creer geom points
geom <- apply(correctionsuniques,1, function(x){
  if(!any(is.na(x["lat"]),is.na(x["lon"]))){
    return(geojsonio::geojson_list(as.numeric(c(x["lon"],x["lat"])))$features[[1]]$geometry)
  } else {
    return(NA)
  }})

crs_ls <- list(type="name",properties=list(name="EPSG:4326"))

# Fusionner les deux listes (geomations + sites)
for(i in 1:length(correctionsuniques_ls)){
  correctionsuniques_ls[[i]]$geom <- geom[i][[1]]
  if(is.list(correctionsuniques_ls[[i]]$geom)){
    correctionsuniques_ls[[i]]$geom$crs <- list(type="name",properties=list(name="EPSG:4326"))
  }
}


correctionsuniques_ls
```



* **7.8** Cette étape est seulement nécessaire si la base de données comprend des colonnes qui ne sont pas dans Coléo

```r
correctionscol <- select(correctionsuniques_ls, cell_id, off_station_code_id, site_code, type, opened_at, geom, notes)
```

**Cette dernière étape injecte les données de la base de données dans Coléo**

```r
rcoleo:::post_sites(correctionstoupload)
```

Bravo ! Vous venez d'injecter vos nouveaux sites dans la base de données Coléo.
