
# tips for working with this table
# use datapasta::fiddle() to fix formatting after an update

#' Table des tables requises par type de campagne
#'
#'
#' @return a tbl_df showing which tables are required for which injection efforts.
coleo_get_required_tables <- function(){

tibble::tribble(
                    ~table, ~végétation, ~végétation_transect, ~sol, ~acoustique_chiroptères, ~acoustique_orthoptères, ~acoustique_oiseaux, ~acoustique_anoures, ~phénologie, ~mammifères, ~papilionidés, ~odonates, ~insectes_sol, ~ADNe, ~zooplancton, ~température_eau, ~température_sol, ~marais_profondeur_température, ~décomposition_sol, ~benthos, ~physicochimie_terrain, ~physicochimie_labo,
                   "cells",           0,                    0,    0,                       0,                       0,                   0,                   0,           0,           0,             0,         0,             0,     0,            0,                0,                0,                              0,                  0,        0,                      0,                   0,
                   "sites",           0,                    0,    0,                       0,                       0,                   0,                   0,           0,           0,             0,         0,             0,     0,            0,                0,                0,                              0,                  0,        0,                      0,                   0,
               "campaigns",           1,                    1,    1,                       1,                       1,                   1,                   1,           0,           1,             1,         1,             1,     1,            1,                0,                0,                              0,                  1,        1,                      1,                   1,
                 "efforts",           1,                    0,    0,                       1,                       1,                   1,                   1,           0,           1,             0,         0,             0,     0,            0,                0,                0,                              0,                  0,        1,                      0,                   0,
            "environments",           0,                    0,    0,                       0,                       0,                   0,                   0,           0,           0,             1,         1,             0,     0,            0,                0,                0,                              0,                  0,        0,                      1,                   1,
                 "devices",           0,                    0,    0,                       1,                       1,                   1,                   1,           0,           1,             0,         0,             0,     0,            0,                0,                0,                              0,                  0,        0,                      0,                   0,
                   "lures",           0,                    0,    0,                       0,                       0,                   0,                   0,           0,           1,             0,         0,             0,     0,            0,                0,                0,                              0,                  0,        0,                      0,                   0,
                   "traps",           0,                    0,    0,                       0,                       0,                   0,                   0,           0,           0,             0,         0,             1,     0,            0,                0,                0,                              0,                  0,        0,                      0,                   0,
               "landmarks",           1,                    0,    1,                       1,                       1,                   1,                   1,           0,           1,             1,         1,             1,     1,            1,                0,                0,                              0,                  0,        0,                      1,                   1,
                 "samples",           0,                    0,    0,                       0,                       0,                   0,                   0,           0,           0,             0,         0,             1,     0,            0,                0,                0,                              0,                  0,        0,                      0,                   0,
            "thermographs",           0,                    0,    0,                       0,                       0,                   0,                   0,           0,           0,             0,         0,             0,     0,            0,                0,                0,                              0,                  0,        0,                      0,                   0,
            "observations",           1,                    1,    1,                       1,                       1,                   1,                   1,           0,           1,             1,         1,             1,     1,            1,                0,                0,                              0,                  1,        1,                      1,                   1,
             "obs_species",           1,                    1,    0,                       1,                       1,                   1,                   1,           0,           1,             1,         1,             1,     0,            1,                0,                0,                              0,                  0,        1,                      0,                   0,
              "attributes",           0,                    0,    0,                       0,                       0,                   0,                   0,           0,           0,             0,         0,             0,     0,            0,                0,                0,                              0,                  0,        0,                      0,                   0,
  "obs_soil_decomposition",           0,                    0,    1,                       0,                       0,                   0,                   0,           0,           0,             0,         0,             0,     0,            0,                0,                0,                              0,                  1,        0,                      0,                   0,
                "obs_lake",           0,                    0,    0,                       0,                       0,                   0,                   0,           0,           0,             0,         0,             0,     0,            0,                0,                0,                              0,                  0,        0,                      1,                   1,
                "obs_edna",           0,                    0,    0,                       0,                       0,                   0,                   0,           0,           0,             0,         0,             0,     1,            0,                0,                0,                              0,                  0,        0,                      0,                   0,
                "obs_soil",           0,                    0,    0,                       0,                       0,                   0,                   0,           0,           0,             0,         0,             0,     0,            0,                0,                0,                              0,                  0,        0,                      0,                   0,
   "obs_temperature_depth",           0,                    0,    0,                       0,                       0,                   0,                   0,           0,           0,             0,         0,             0,     0,            0,                0,                0,                              0,                  0,        0,                      0,                   0,
                   "media",           0,                    0,    0,                       0,                       0,                   0,                   0,           0,           1,             0,         0,             0,     0,            0,                0,                0,                              0,                  0,        0,                      0,                   0
  )
}
