
# tips for working with this table
# use datapasta::fiddle() to fix formatting after an update

# table = the table in the database
# input_column = the column name in the input
# db_column = the column name to be injected into the database
# required_class = the class-checking function required
# legal_values = a vector of what values it is allowed to have.

#' Table contenant pour chaque table de la base de données les noms de colonnes, les champs correspondants dans la base de données, les champs obligatoires, la classe des données par colonne et les valeurs possibles par colonnes
#'
#' @param
#'
#' @return
#' @export
coleo_get_name_table <- function(){
tibble::tribble(
                   ~table,                ~input_column,            ~db_column, ~is_required,            ~required_class,                                                                                                                                                                                                                                              ~legal_values,
                  "sites",                  "site_code",           "site_code",         TRUE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                  "sites",                  "site_name",           "site_name",         TRUE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                  "sites",                  "site_type",                "type",         TRUE, .Primitive("is.character"),                                                                                                                                                                     c("lac", "rivière", "forestier", "marais", "marais côtier", "toundrique", "tourbière"),
                  "sites",             "site_opened_at",           "opened_at",         TRUE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                  "sites",                   "site_lat",                 "lat",         TRUE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
                  "sites",                   "site_lon",                 "lon",         TRUE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
                  "sites",                 "site_notes",               "notes",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
              "campaigns",                  "camp_type",                "type",         TRUE, .Primitive("is.character"),                          c("végétation", "végétation_transect", "sol", "acoustique", "phénologie", "mammifères", "papilionidés", "odonates", "insectes_sol", "ADNe", "zooplancton", "température_eau", "température_sol", "marais_profondeur_température"),
              "campaigns",               "technician_1",        "technician_1",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
              "campaigns",               "technician_2",        "technician_2",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
              "campaigns",           "camp_date_opened",           "opened_at",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
              "campaigns",           "camp_date_closed",           "closed_at",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
              "campaigns",                 "camp_notes",               "notes",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                "efforts",            "efforts_stratum",             "stratum",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                            c("arbres", "arbustes/herbacées", "bryophytes"),
                "efforts",         "efforts_time_start",          "time_start",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                "efforts",        "efforts_time_finish",         "time_finish",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                "efforts",          "efforts_samp_surf",           "samp_surf",        FALSE,   .Primitive("is.integer"),                                                                                                                                                                                                                                                         NA,
                "efforts",     "efforts_samp_surf_unit",      "samp_surf_unit",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                      c("cm2", "m2", "km2"),
                "efforts",              "efforts_notes",               "notes",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
            "environment",                       "wind",                "wind",        FALSE,   .Primitive("is.integer"),                                                                                                                                                                                                                                                        1:5,
            "environment",                        "sky",                 "sky",        FALSE,   .Primitive("is.integer"),                                                                                                                                                                                                                                                        1:5,
            "environment",                     "temp_c",              "temp_c",        FALSE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
                "devices",              "sd_card_codes",       "sd_card_codes",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                "devices",                   "cam_code",            "cam_code",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                "devices",                   "cam_h_cm",            "cam_h_cm",        FALSE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
                "devices",            "mic_logger_code",     "mic_logger_code",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                "devices",               "mic_acc_code",        "mic_acc_code",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                "devices",               "mic_h_cm_acc",        "mic_h_cm_acc",        FALSE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
                "devices",             "mic_ultra_code",      "mic_ultra_code",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                "devices",            "mic_orientation",     "mic_orientation",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                              c("n", "s", "e", "o", "ne", "no", "se", "so"),
                  "lures",                       "lure",                "lure",        FALSE,   .Primitive("is.integer"),                                                                                                                                                                                                                                                         NA,
                  "lures",          "lure_installed_at",        "installed_at",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                  "traps",                  "trap_code",           "trap_code",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                  "traps",                "traps_notes",               "notes",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
              "landmarks",                  "tree_code",           "tree_code",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
              "landmarks",             "land_taxa_name",           "taxa_name",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
              "landmarks",                   "land_dbh",                 "dbh",        FALSE,   .Primitive("is.integer"),                                                                                                                                                                                                                                                         NA,
              "landmarks",                   "dbh_unit",            "dbh_unit",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                         c("mm", "cm", "m"),
              "landmarks",                  "land_axis",                "axis",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                         c("n", "se", "so"),
              "landmarks",                "land_azimut",              "azimut",        FALSE,   .Primitive("is.integer"),                                                                                                                                                                                                                                                         NA,
              "landmarks",              "land_distance",            "distance",        FALSE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
              "landmarks",         "land_distance_unit",       "distance_unit",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                         c("mm", "cm", "m"),
              "landmarks",                   "land_lat",                 "lat",        FALSE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
              "landmarks",                   "land_lon",                 "lon",        FALSE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
              "landmarks",                  "land_type",                "type",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                c("gps", "arbre", "gps+arbre", "borne_axe", "thermographe"),
              "landmarks",                 "land_notes",               "notes",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                "samples",                "sample_code",         "sample_code",         TRUE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                "samples",                  "date_samp",           "date_samp",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
                "samples",                 "samp_notes",               "notes",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
           "thermographs",                "landmark_id",         "landmark_id",         TRUE,   .Primitive("is.integer"),                                                                                                                                                                                                                                                         NA,
           "thermographs",             "thermograph_no",      "thermograph_no",         TRUE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
           "thermographs",               "thermo_depth",               "depth",        FALSE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
           "thermographs",              "thermo_height",              "height",        FALSE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
           "thermographs",           "thermo_is_on_bag",           "is_on_bag",        FALSE,   .Primitive("is.logical"),                                                                                                                                                                                                                                                         NA,
           "thermographs",             "thermo_shading",             "shading",        FALSE,   .Primitive("is.integer"),                                                                                                                                                                                                                                                        1:5,
           "thermographs",               "thermo_notes",               "notes",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
           "observations",                   "date_obs",            "date_obs",         TRUE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
           "observations",                   "time_obs",            "time_obs",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
           "observations",                "obs_stratum",             "stratum",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                  c("arborescente", "arbustive", "herbacées", "bryophytes"),
           "observations",                   "obs_axis",                "axis",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                         c("n", "se", "so"),
           "observations",               "obs_distance",            "distance",        FALSE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
           "observations",          "obs_distance_unit",       "distance_unit",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                         c("mm", "cm", "m"),
           "observations",                  "obs_depth",               "depth",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
           "observations",               "obs_is_valid",            "is_valid",         TRUE,   .Primitive("is.logical"),                                                                                                                                                                                                                                                         NA,
           "observations",          "obs_campaign_info",       "campaign_info",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
           "observations",                  "obs_notes",               "notes",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
            "obs_species",              "obs_taxa_name",           "taxa_name",         TRUE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
            "obs_species",               "obs_variable",            "variable",         TRUE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
            "obs_species",                  "obs_value",               "value",        FALSE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
             "attributes",               "att_variable",            "variable",         TRUE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
             "attributes",            "att_description",         "description",         TRUE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
             "attributes",                   "att_unit",                 "unt",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
            "ref_species",              "ref_taxa_name",                "name",         TRUE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
            "ref_species",              "vernacular_fr",       "vernacular_fr",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
            "ref_species",              "vernacular_en",       "vernacular_en",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
            "ref_species",              "ref_taxa_rank",                "rank",        FALSE, .Primitive("is.character"), c("sous-embranchement", "embranchement", "sous-classe", "classe", "sous-ordre", "ordre", "super-famille", "famille", "genre", "espèce", "sous-espèce", "variété", "complexe", "genre_hybride", "espèce_hybride", "variété_hybride", "sous-espèce_hybride"),
            "ref_species",          "ref_taxa_category",            "category",        FALSE, .Primitive("is.character"),                                                                                                                                         c("poissons", "plantes", "oiseaux", "amphibiens", "arthropodes", "mammifères", "reptiles", "autres", "mollusques"),
            "ref_species",               "ref_taxa_tsn",                 "tsn",         TRUE,   .Primitive("is.integer"),                                                                                                                                                                                                                                                         NA,
  "obs_soil_decompsition",              "decomp_bag_no",              "bag_no",         TRUE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
  "obs_soil_decompsition",                "decomp_type",                "type",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
  "obs_soil_decompsition",                 "decomp_lat",                 "lat",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
  "obs_soil_decompsition",                 "decomp_lon",                 "lon",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
  "obs_soil_decompsition",            "decomp_date_end",            "date_end",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
  "obs_soil_decompsition",        "decomp_start_weight",        "start_weight",         TRUE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
  "obs_soil_decompsition", "decomp_end_weight_with_bag", "end_weight_with_bag",        FALSE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
  "obs_soil_decompsition",      "decomp_end_weight_tea",      "end_weight_tea",        FALSE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
  "obs_soil_decompsition",             "decomp_shading",             "shading",        FALSE,   .Primitive("is.integer"),                                                                                                                                                                                                                                           c(1, 2, 3, 4, 5),
  "obs_soil_decompsition",        "decomp_human_impact",        "human_impact",        FALSE,   .Primitive("is.integer"),                                                                                                                                                                                                                                           c(1, 2, 3, 4, 5),
               "obs_edna",             "edna_taxa_name",           "taxa_name",         TRUE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA,
               "obs_edna",        "edna_sequence_count",      "sequence_count",        FALSE,   .Primitive("is.numeric"),                                                                                                                                                                                                                                                         NA,
               "obs_edna",                  "type_edna",           "type_edna",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                     c("confirmé", "probable", "improbable", "non-poisson"),
               "obs_edna",                 "edna_notes",               "notes",        FALSE, .Primitive("is.character"),                                                                                                                                                                                                                                                         NA
  )


}
